### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AKCore** [zacharypetersen1/FlexibleCelShader#1]
Is there anyway to request the Outline Shader with Alpha Transparency? 
The shader as a whole is an amazing asset, I'm truly surprised that its free. 
And on that note i would be glad to pay you for your time to implement it :)

**Comment by zacharypetersen1** [comment]
Added Shader under category "OutlineOnlyShader/TransparentOutline" (file is FlexibleCelShader/Shaders/TransparentOutline.shader) that renders a transparent outline. To combine this effect with FCS, create an extra material slot on your mesh and place a CelNoOutline material in one slot and then put a TransparentOutline material in the other slot. I didn't bother with hooking the TransparentOutline shader into the preset system because it only has the color and size properties. If needed you can right click on the material in the inspector and copy / paste material properties.
![image](https://user-images.githubusercontent.com/10237255/106546676-9585bb80-64c0-11eb-86f3-76aea9147e5b.png)

Cheers!

**Comment by AKCore** [comment]
I think I might have elaborated it wrongly. 
I just wanted to have the standard outline shader with alpha transparency for things like glass and such.
I tried to do it, and it managed to get the front face gone, but the back was still black. 
I am super new to working with shaders so it seems to be the impossible problem for me. :)

**Comment by zacharypetersen1** [comment]
Got it, I think I understand. Also, I just noticed that the old versions of the shader already supported transparent outlines -___- woops it's been a while. Added CelTransparentNoOutline and CelTransparentOutline shaders that provide transparency to both the outline and the main body part of the shader and also removed the outline only shader that I added in the last commit. To change the opacity of the main part of the shader, modify the alpha channel of the Global Color Modifier. To change the opacity of the outline, modify the alpha of the outline color.
![image](https://user-images.githubusercontent.com/10237255/107174992-826f6180-6980-11eb-802f-1912dbfd92a9.png)

Will note one more thing: I left back face culling "on" in the pass that draws the main cel shaded part of the material. This means that you will only see front faces, however if you want to be able to see both the front and back faces of cel shaded part of the material since the material can now be transparent, go to the pass that renders the cel shaded part and turn culling off for that pass (line 40 in CelTransparentOutline.shader in this commit, change "Cull Back" to "Cull Off"

Cheers!
